on:
  push:
    branches:
      - main
      - production
    paths:
      - core/**/*
      - .github/workflows/api.yml

jobs:
  core-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 16
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.0.2
      - name: Build
        run: gradle --parallel --build-cache -Dorg.gradle.console=plain -Dorg.gradle.daemon=false shadowJar

  core-test:
    runs-on: ubuntu-latest
    needs: core-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 16
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.0.2
      - name: Test core tests
        run: |
          gradle --parallel --build-cache -Dorg.gradle.console=plain -Dorg.gradle.daemon=false shadowJar
          gradle --parallel --no-rebuild -Dorg.gradle.console=plain -Dorg.gradle.daemon=false test --info